name: app
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - uwsgi
  - pip
  - ipopt
  - glpk
  - flask
  - gunicorn
  - pandas
  - matplotlib
  - scikit-learn
  - pyomo
  - pip:
      - -r requirements.txt
